### ISSUE TITLE
Dataset link

### ISSUE THREAD

**Issue by HeaIn** [ciber-lab/pictor-yolo#5]
Hi,
Thank you for your great work!

I was trying to download the dataset, but the link requires an account for University of Colorado Boulder.
Can you share other link for the dataset?

**Comment by ciber-lab** [comment]
Thanks for bringing this to our attention. The issue has been fixed. Please
try again and let us know if you have difficulty accessing the content.

**Comment by HeaIn** [comment]
Thank you for fixing it.
However, I'm still unable to access the dataset due to the following error message.
Would you be able to review it once more?

![error_page](https://github.com/user-attachments/assets/be849aa4-2831-4be4-88ca-db1a67a8af30)

**Comment by ciber-lab** [comment]
Apparently, the OneDrive server links were broken. Please try again as we
have.migratws our datasets back to Google Drive.

**Comment by HeaIn** [comment]
I have checked the link, and everything seems to be working perfectly now.
Thank you for addressing the problem.
